---
title: "R Community of Practice"
subtitle: "Week 3"
format: 
  revealjs:
    editor: source
    theme: custom.scss
    logo: rcop_hex_logo.png
---

## Learning Goals

::: incremental

1. Become familiar with the basic components of a **`ggplot2`** graph
1. Understand the concept of "aesthetic mapping"
1. Use **`ggplot2`** to create bar graphs
1. Use **`ggplot2`** to customize graphs

:::

## The Data {.smaller}

**Scenario:** We want to visualize the `all_workshops` data frame we created in Week 1. 

We'll complete the following tasks:

:::incremental
1. Create a basic bar chart comparing workshop attendance among the various schools.
2. Create a grouped bar chart comparing workshop attendance among the schools and university roles. 
3. Add titles and labels to our graph
4. Adjust the color palette
5. Choose a theme
6. Output graph to jpeg file

:::

## `ggplot2` Basics

The "gg" in `ggplot2` refers to the "grammar of graphics". 

All `ggplot2` graphs start with the same basic template:

```
<DATA> %>%
    ggplot(aes(<MAPPINGS>)) +
    <GEOM_FUNCTION>() +
    <Additional GEOMS, SCALES, THEMES, etc. . . >

```

## Helpful Resources

- [**`ggplot2`** documentation](https://ggplot2.tidyverse.org/)
- [R for Data Science](https://r4ds.had.co.nz/)
- [R Graph Gallery](https://r-graph-gallery.com/)
- [R Graphics Cookbook](https://r-graphics.org/)
- [R Graph Gallery Color Section](https://r-graph-gallery.com/ggplot2-color.html)
- [**`ggplot2`** Aesthetic Specifications](https://ggplot2.tidyverse.org/articles/ggplot2-specs.html)