project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "Week01/*.qmd"
    - "Week02/*.qmd"
    - "Week03/*.qmd"
    - "Week04/*.qmd"

website:
  title: "NNLM + CDABS R Community of Practice"
  navbar:
    page-navigation: true
    back-to-top-navigation: true
    pinned: true
    background: primary
    search: false
    left:
      - text: Week01
        file: Week01/week01_lesson.qmd
      - text: Week02
        file: Week02/week02_lesson.qmd
      - text: Week03
        file: Week03/week03_lesson.qmd
      - text: Week04
        file: Week04/week04_lesson.qmd

format:
  html:
    theme: yeti
    editor: source
    toc: true